default_agent: agentcore
agents:
  agentcore:
    name: agentcore
    entrypoint: agentcore.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::871346884868:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-5f877bc76c
      execution_role_auto_create: false
      account: '871346884868'
      region: ap-south-1
      ecr_repository: 871346884868.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-agentcore
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
